---

name: Pull request code validation and building (Main branch)
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/oci-docker-build.yaml@25c677035c68570a775bfeee4fb32f806a428ab5
    with:
      OCI_REGISTRY: ghcr.io
      OCI_IMAGE: ${{ github.repository }}
    secrets:
      OCI_USERNAME: ${{ github.actor }}
      OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
