---
name: Curator release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"

  helm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
